# Generated by Django 4.2.7 on 2025-10-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_allow_null_time_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberprofile',
            name='monday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='monday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='tuesday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='tuesday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='wednesday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='wednesday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='thursday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='thursday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='friday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='friday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='saturday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='saturday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='sunday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='sunday_end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]