# Generated by Django 4.2.7 on 2025-10-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_allow_null_barber_time_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
